# permissions for end users to view firewallzones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: firewallzone-viewer-role
rules:
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - firewallzones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - firewallzones/status
  verbs:
  - get
