# permissions for end users to edit firewallsnats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: firewallsnat-editor-role
rules:
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - firewallsnats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - firewallsnats/status
  verbs:
  - get
