# permissions for end users to view firewalldnats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: firewalldnat-viewer-role
rules:
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - firewalldnats
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - firewalldnats/status
  verbs:
  - get
