# permissions for end users to edit firewallforwardings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: firewallforwarding-editor-role
rules:
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - firewallforwardings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - firewallforwardings/status
  verbs:
  - get
