# permissions for end users to edit firewallzones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: firewallzone-editor-role
rules:
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - firewallzones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - firewallzones/status
  verbs:
  - get
