# This patch add annotation to admission webhook config and
# the variables $(CERTIFICATE_NAMESPACE) and $(CERTIFICATE_NAME) will be substituted by kustomize.
#apiVersion: admissionregistration.k8s.io/v1beta1
#kind: MutatingWebhookConfiguration
#metadata:
#  name: mutating-webhook-configuration
#  annotations:
#    cert-manager.io/inject-ca-from: $(CERTIFICATE_NAMESPACE)/$(CERTIFICATE_NAME)
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: $(CERTIFICATE_NAMESPACE)/$(CERTIFICATE_NAME)
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURTRENDQWpDZ0F3SUJBZ0lSQU5YNnhsbStSeHdYd0EzT1g2TTBZQ3N3RFFZSktvWklodmNOQVFFTEJRQXcKRnpFVk1CTUdBMVVFQ2hNTVkyVnlkQzF0WVc1aFoyVnlNQjRYRFRJd01EVXdOekE1TURnek5sb1hEVEl3TURndwpOVEE1TURnek5sb3dGekVWTUJNR0ExVUVDaE1NWTJWeWRDMXRZVzVoWjJWeU1JSUJJakFOQmdrcWhraUc5dzBCCkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXpkTXRieExUbGFiRmhranR0WGs4NlR1TldES0dET0Z2UGo1dGRCSzEKakFCTnFKa2xVL1kvSVdrMUswNE10RkJmYmJLczlzN05weWtaSU5BejBlWSt2S3VFd29UMlozZ1NXRFpYcjFGRgpOWVZhRU52Tk5sNUtsaE5FYU5CMzZtWTAvdkNCT3orWGJ4cjM1SE5OSzVqV3pKY2o5b2RVM1VVOWdkeHVhMWNWCkIyNjMwcG5LZGNKMmNEU2dzeDRTbVVucFlzdXI0bFFZQ1BIUWRQNTdFajFWd1hhUyt4dmRVdnFidW1MU3UyaGIKWnBXdTdMNlNLYittaHUrTDJRRG9ScytnS0ZiZFVIZWJGMkhlMlNvV2tEc0g2eU14aGpvZjFuWVJmK2sxT0gvTgowOUJXSlUvZThVNzk5c2Q5czJ5bGJYVU1JdXNaTVU1cW5iWnRqN2I2U2hyYjRRSURBUUFCbzRHT01JR0xNQTRHCkExVWREd0VCL3dRRUF3SUZvREFNQmdOVkhSTUJBZjhFQWpBQU1Hc0dBMVVkRVFSa01HS0NLSE5rWlhkaGJpMTMKWldKb2IyOXJMWE5sY25acFkyVXVjMlJsZDJGdUxYTjVjM1JsYlM1emRtT0NObk5rWlhkaGJpMTNaV0pvYjI5cgpMWE5sY25acFkyVXVjMlJsZDJGdUxYTjVjM1JsYlM1emRtTXVZMngxYzNSbGNpNXNiMk5oYkRBTkJna3Foa2lHCjl3MEJBUXNGQUFPQ0FRRUFneDBMS242dzNMSlFRUlhPczE3N2kvcW1BOXNjTUNFeHB3SE5ZSUlLRC9EbWEvVnEKcHJxS1BjbkpiVTh0bnpncTBBeDY4TjliN0tEbFNDbXFKZEcrWmxES21PbzRKK1ZzKy9kVWdINU41M3d4RmsrVQpFamRhOWV3YmFVZ3pVTTMxakFTK1lqaWFUY3RVQk01UDFzTURqODYyNjVSS25qU3ZzaDVCSndaaDJtT1RJNGtOCnM1NFd4Yk0yUTNwcUdtdUxKTzU3ZkhJaWxaREc3VWdvTHFtT0dHVVhFL1g0TVQ2Ly9qdTJ3Qlp3NHpVbU5jWjYKMEJkOTQ2SU4yS1huY2lWSTBBUnUycWNocE1tNmhHM2hiS0hKOHdIRUhmNFE4eWhITWZtdE5yMFBscEpKcFZtYQphSFNtc0Y0cVJoZ3B5aXZkdUdyOC9RWXNjb3NIWGM0UVVwanFJZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K

